### ISSUE TITLE
[Ola C7.03] feat-cuentos-spread-inmersivo: immersive spread reader at /leer/ (LectorInmersivo)

### ISSUE THREAD

**Issue by iberi22** [iberi22/worldexams#1332]
# [Ola C7.03] feat-cuentos-spread-inmersivo: immersive spread reader at /leer/ (LectorInmersivo)

## 1. Current State (measurable)

- Full story text renders as a web article on `saberparatodos/src/pages/cuentos/[slug].astro` (adult chrome, breadcrumbs/footer context): there is no immersive spread — no cream card, no gold filigree, no dots pagination.
- `saberparatodos/src/pages/cuentos/[slug]/leer/` does NOT exist (0 files): no dedicated reading route.
- `saberparatodos/src/components/cuentos/` contains no `LectorInmersivo*` file: the working reader islands are `lector/CuentoReader.svelte` (pagination/autoplay), `lector/read-aloud.ts` (Web Speech), `lector/QuizCuento.svelte`, `lector/EscenaInteractiva.svelte` — functional but not the evidence spread.
- Narration MP3s (`public/audio/cuentos/<slug>/pN.mp3`) are generated by a separate track and may NOT exist when this issue lands: the reader must keep the Web Speech path as the working default and must not hard-depend on MP3 files (no broken `<audio>` tags for missing files).
- Evidence: `docs/CUENTOS/REDISENO_STORYCOMET.md` §1.4 + §2 C7.03 (spread inmersivo: tarjeta crema + filigrana dorada en esquinas + Andika 24px + dots + flechas grandes, SIN chrome adulto).

## 2. Desired State

- New route `saberparatodos/src/pages/cuentos/[slug]/leer/` (Astro; `getStaticPaths` reused from the story pages pattern): night shell (C7.01) + `noindex` + `LectorInmersivo` for the slug, zero nav/breadcrumbs/footer.
- New component `saberparatodos/src/components/cuentos/lector/LectorInmersivo.svelte` (Svelte 5 runes): one immersive spread per page — cream `#FFF9DC` card, original inline-SVG gold `#D4A94E` filigree corners (hand-drawn-feel, free, no stock), body text in Andika 24px (`var(--font-cuentos-cuerpo)` with system fallback so it works before/after C7.04), dots pagination (one dot per page, current highlighted, click-to-jump), big prev/next arrow buttons (≥56px, wooden-toy style consistent with the shell), keyboard arrows + swipe support, scene art via existing `EscenaInteractiva` island, quiz via existing `QuizCuento` island at story end, read-aloud via the existing read-aloud hook (Web Speech default; MP3-by-page is a later enhancement — detect file presence defensively, never assume it).
- Pagination state persists through the existing progreso store (page N survives reload); reduced-motion freezes transitions (instant page swap, static final pose).
- Forward-compatible slots for per-page `hint`/`words` (content v2, separate issue): render them IF present in the pack object, require nothing new — pack v1 stories render fully without them.

## 3. Web Research (4–6 queries)

1. Svelte 5 runes (`$state` page index, `$derived` current page, `$effect` progress persist + key handlers) — https://svelte.dev/docs/svelte/runes
2. Astro dynamic nested routes + `getStaticPaths` (`[slug]/leer/`) — https://docs.astro.build/en/guides/routing/#dynamic-routes
3. Dots pagination a11y: `role="tablist"`/arrow-key pattern or labelled buttons with `aria-current` — https://www.w3.org/WAI/ARIA/apg/patterns/tabs/
4. Touch swipe without libraries: `touchstart`/`touchend` delta threshold + `prefers-reduced-motion` bypass — https://developer.mozilla.org/en-US/docs/Web/API/Element/touchstart_event
5. `prefers-reduced-motion` page transitions — https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion
6. Web Speech API voices for `es` (`speechSynthesis.getVoices()`, async voice loading) — https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis/getVoices (supports the Web Speech default path; no new deps)

## 4. Agent Session Prompt

> You are implementing C7.03 (feat-cuentos-spread-inmersivo) in `/home/belal/proyectosSWAL/apps/worldexams`.
> READ FIRST (full files, before any edit): `saberparatodos/src/components/cuentos/lector/CuentoReader.svelte` (pagination/store/read-aloud wiring), `saberparatodos/src/components/cuentos/lector/read-aloud.*`, `saberparatodos/src/pages/cuentos/[slug].astro` (getStaticPaths + pack loading), `docs/CUENTOS/REDISENO_STORYCOMET.md` (§1.4, §2 C7.03), `docs/CUENTOS/01_DIRECCION_ARTE.md` (§2 palette, §4–§5 escenas/animaciones, §7 checklist), `docs/CUENTOS/02_COPYRIGHT_Y_FORMATO.md` (§1–§2), `docs/CUENTOS/WAVE_PLAN.md` (privacy section).
> Task: (1) create `saberparatodos/src/components/cuentos/lector/LectorInmersivo.svelte` (Svelte 5 runes; cream card + inline-SVG gold filigree corners + Andika 24px via CSS var with fallback + dots pagination + big arrows ≥56px + keyboard/swipe; reuse `EscenaInteractiva`, `QuizCuento`, read-aloud hook, progreso store — no logic forks). (2) create route `saberparatodos/src/pages/cuentos/[slug]/leer/` (Astro; reuse getStaticPaths pattern; night shell; `noindex`; zero chrome). (3) tolerant `hint`/`words` slots (render if present, require nothing). (4) Web Speech stays the working narration default; do NOT hard-code `public/audio/cuentos/<slug>/pN.mp3` URLs (files may not exist yet — any MP3 probing must fail silent with Speech fallback, never a broken player). (5) add e2e `saberparatodos/tests/e2e/cuentos-leer.spec.ts` (desktop+mobile, screenshots, 0 console errors). (6) run all checks in §11.
> Constraints: BR-03 (zero tokens/telemetry), BR-07 (no login gate), unlisted (noindex, no sitemap/nav additions), neutral Spanish only, copyright header on every new file, reduced-motion respected, free assets only (original inline SVG filigree, no stock/downloads). Do NOT touch `features.json` or anything under `questions_data/cuentos/`. Svelte runes only; `.astro` files use ternaries/`.map`, never `{#if}`/`{#each}`; absolute import paths from the package root.

## 5. Existing Code Patterns

- `lector/CuentoReader.svelte`: pagination state, autoplay timer, progreso persistence, logro evaluation, keyboard handling — port this wiring into `LectorInmersivo` (same stores, same event names); do not fork parallel progress logic.
- `lector/read-aloud.*`: Web Speech hook (es voices, rate control) — consume as-is; the MP3 upgrade belongs to a later audio issue, not this one.
- `lector/QuizCuento.svelte` + `lector/EscenaInteractiva.svelte`: end-of-story quiz and per-page tactile scene — embed both, pass through existing props.
- `[slug].astro` data loading: `getStaticPaths` + static-pack JSON read — duplicate the pattern for `[slug]/leer/` (new directory with its own Astro file(s), same loader).
- C7.01 shell + C7.04 font var: render inside `CuentosShell`/HUD and use `var(--font-cuentos-cuerpo, <system fallback stack>)` so the spread works with or without C7.04 merged.

## 6. Acceptance Criteria (command-verifiable)

1. `ls "saberparatodos/src/pages/cuentos/[slug]/leer/"` → route file(s) exist; `ls saberparatodos/src/components/cuentos/lector/LectorInmersivo.svelte` → exists.
2. Spread visuals: `grep -rEn "#FFF9DC|#D4A94E" saberparatodos/src/components/cuentos/lector/LectorInmersivo.svelte` → ≥2; filigree is inline SVG (`<svg` present in the component, zero external image refs: `grep -rEn "http.*\\.(png|jpg|svg)|base64" .../LectorInmersivo.svelte` → exit 1).
3. Body text uses the font var: `grep -c "font-cuentos-cuerpo" .../LectorInmersivo.svelte` → ≥1; computed `font-size` of spread text ≥24px at desktop width (asserted in e2e via `evaluate`).
4. Dots pagination: e2e counts dots == page count from pack JSON; clicking dot 5 lands on page 5; big arrows advance/retreat one page; ArrowRight/ArrowLeft keys work; swipe changes page on mobile viewport.
5. Quiz appears at story end (existing `QuizCuento` island renders after the last page) and read-aloud controls work with Web Speech (no `public/audio` dependency: `grep -rEn "public/audio|/audio/cuentos" .../LectorInmersivo.svelte "src/pages/cuentos/[slug]/leer/"` → exit 1 OR any reference is a guarded optional enhancement with Speech fallback — e2e with empty `public/audio/cuentos/` still narrates and shows 0 failed requests).
6. `hint`/`words` tolerance: pack v1 (no such fields) renders fully; a synthetic pack object WITH `hint`/`words` renders them (unit- or e2e-level assertion with fixture, no content files touched).
7. `npx playwright test tests/e2e/cuentos-leer.spec.ts` on desktop + mobile → PASS with `leer-desktop.png` + `leer-mobile.png`; console-error + `pageerror` collectors → 0 on both viewports.
8. Zero adult chrome on `/leer/`: e2e asserts no site nav/breadcrumbs/footer; `grep -rEn "noindex"` on the leer route file(s) → ≥1.
9. `grep -rEn "prefers-reduced-motion" .../LectorInmersivo.svelte` → ≥1; reduced-motion emulation → instant page swap (no transform transition).
10. `grep -rEn "fetch\(|sendBeacon|analytics|gtag|plausible|posthog|supabase" .../LectorInmersivo.svelte` → exit 1 (BR-03); veto-word grep (§11) → exit 1 (neutral Spanish).
11. `node scripts/validate_cuentos.js` → 0 errors, 10/10 (untouched content still green).

## 7. Files + Risk

| File | Change | Risk |
|------|--------|------|
| `saberparatodos/src/components/cuentos/lector/LectorInmersivo.svelte` | NEW (~280 lines) | High — the visual core of C7; keep logic delegated to existing islands, style local |
| `saberparatodos/src/pages/cuentos/[slug]/leer/*` | NEW route (~60 lines) | Low — mirrors existing loader pattern |
| `saberparatodos/tests/e2e/cuentos-leer.spec.ts` | NEW (~150 lines) | None |
| `lector/CuentoReader.svelte`, `read-aloud.*`, `QuizCuento.svelte`, `EscenaInteractiva.svelte`, progreso store | READ-ONLY (import, do not fork) | Any logic change here is scope creep — FAIL if diff touches them beyond imports |
| Filigree SVG | Inline in component (original, ~40 lines) | Low — must be original art, no stock |

## 8. DO NOT Touch

- `features.json` (never edit it here).
- Anything under `questions_data/cuentos/`: no text/quiz/SVG edits, no `hint`/`words` backfill (content v2 is a separate issue).
- Validator, pack generator, static packs; `CuentoReader`/`QuizCuento`/`EscenaInteractiva`/read-aloud/progreso internals.
- `public/audio/cuentos/`: do not add placeholder MP3s, do not commit binaries.
- The door page `[slug].astro` (C7.02 owns it); the shelf; sitemap/robots/nav.

## 9. Anti-Hallucination Rules

1. READ-first: no spread code before reading `CuentoReader.svelte` (full — it is the wiring spec), `read-aloud.*`, `[slug].astro` (loader section), and `REDISENO_STORYCOMET.md` §1.4 + §2 C7.03; list the reused props/store functions by name in the PR description.
2. Svelte 5 runes only: zero `export let`, `$:` labels, `createEventDispatcher` in `LectorInmersivo.svelte` (grep-verified). (`{#if}`/`{#each}` blocks ARE legal Svelte — the ban below is `.astro`-only.)
3. `.astro` files use ternaries and `.map()`; Svelte-only block syntax (`{#if}`, `{#each}`, `{#await}`) inside any `.astro` file is a hard FAIL.
4. Absolute import paths from the package root or repo alias; no invented aliases; every imported island path must `ls`-verify (paste proof in PR).
5. No new npm dependencies, no asset downloads, no Google-Fonts links; filigree must be original inline SVG. Never invent pack fields — `hint`/`words` access must be optional-chained with v1-safe fallbacks. Missing MP3s are an expected state, not an error: any audio probing must fail silent to Web Speech.

## 10. PR Delivery Requirements (anti-empty-PR)

- One PR from `feat/c7-03-spread-inmersivo`; review-ready push contains component + route + e2e + screenshots — no empty/scaffold PRs.
- Description includes: linked issue, reused islands/props/stores list, §11 outputs pasted, `leer-desktop.png` + `leer-mobile.png` attached, import-path `ls` proof.
- Rebased on default branch; CI green; no unrelated files; checklist (BR-03/BR-07, unlisted, neutral Spanish, copyright headers, reduced-motion, no MP3 hard-dependency) ticked with evidence.

## 11. Verification (bash — run inside `saberparatodos/` unless noted)

```bash
ls "src/pages/cuentos/[slug]/leer/" src/components/cuentos/lector/LectorInmersivo.svelte
grep -rEn "export let|\\$:|createEventDispatcher" src/components/cuentos/lector/LectorInmersivo.svelte; test $? -eq 1
grep -rEn "{#if}|{#each}|{#await}" "src/pages/cuentos/[slug]/leer/"*; test $? -eq 1
grep -rEn "fetch\(|sendBeacon|analytics|gtag|plausible|posthog|supabase" src/components/cuentos/lector/LectorInmersivo.svelte; test $? -eq 1
grep -rEn "vos |tenés|hacé|mirá|che |parce|chido|chévere|bacán|pesos|dólares|euros" src/components/cuentos/lector/LectorInmersivo.svelte "src/pages/cuentos/[slug]/leer/"*; test $? -eq 1
node scripts/validate_cuentos.js
npx astro check
npx playwright test tests/e2e/cuentos-leer.spec.ts
```

## 12. Dependencies & Merge Order

- Depends on waves C1–C5 merged (reader islands, quiz, hotspots, progreso, read-aloud, packs) + C7.01 shell (renders inside it).
- C7A order: merge AFTER C7.01, BEFORE C7.02 (the door's primary button targets this route). C7.04 (fonts) may land before or after — the component's font-var-with-fallback works either way. Order: C7.01 → C7.04 → C7.03 → C7.02.

## 13. Failure Recovery

- If swipe handling causes flaky e2e: keep buttons + keyboard as the supported path, gate swipe behind a `data-swipe` flag, and note it in the PR (do not block the merge on gesture polish).
- If `getStaticPaths` for the nested route duplicates loader code painfully: extract a shared `src/lib/cuentos/ruta-lectura.ts` helper used by both `[slug]` and `[slug]/leer/` (small, tested, no logic change).
- If Web Speech voices are missing in headless CI (flaky narration assertions): assert player state transitions (idle→playing→paused) and highlight-class application on a synthetic timer instead of real audio output; document the CI limitation in the spec file.
